# Generated by Django 5.1.7 on 2025-03-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
