# Generated by Django 5.1.7 on 2025-03-27 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_created_at_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=19),
        ),
    ]
